// [POM-APPLIED]
import { test, expect } from '@playwright/test';
import path from 'path';
import * as stepGroups from '../../../src/helpers/step-groups';
import { ChaseFieldNamePage } from '../../../src/pages/correspondant/chase-field-name';
import { CorrespondentPortalPage } from '../../../src/pages/correspondant/correspondent-portal';
import { DuplicatecopyButtonPage } from '../../../src/pages/correspondant/duplicatecopy-button';
import { EnumerationMappingButtonPage } from '../../../src/pages/correspondant/enumeration-mapping-button';
import { ExitButtonPage } from '../../../src/pages/correspondant/exit-button';
import { ImportRulePage } from '../../../src/pages/correspondant/import-rule';
import { MapHeadersButtonPage } from '../../../src/pages/correspondant/map-headers-button';
import { P1MoreButtonPage } from '../../../src/pages/correspondant/p-1-more-button';
import { P24UnitDropdownPage } from '../../../src/pages/correspondant/p-24-unit-dropdown';
import { RulesAndActionsButtonPage } from '../../../src/pages/correspondant/rules-and-actions-button';
import { RulesAndActionsPage } from '../../../src/pages/correspondant/rules-and-actions';
import { SaveAndPublishButtonPage } from '../../../src/pages/correspondant/save-and-publish-button';
import { SpinnerPage } from '../../../src/pages/correspondant/spinner';
import { StatusInactive2Page } from '../../../src/pages/correspondant/status-inactive--2';
import { StatusInactivePage } from '../../../src/pages/correspondant/status-inactive-';

test.describe('REG_Bid Maps', () => {
  let vars: Record<string, string> = {};
  let chaseFieldNamePage: ChaseFieldNamePage;
  let correspondentPortalPage: CorrespondentPortalPage;
  let duplicatecopyButtonPage: DuplicatecopyButtonPage;
  let enumerationMappingButtonPage: EnumerationMappingButtonPage;
  let exitButtonPage: ExitButtonPage;
  let importRulePage: ImportRulePage;
  let mapHeadersButtonPage: MapHeadersButtonPage;
  let p1MoreButtonPage: P1MoreButtonPage;
  let p24UnitDropdownPage: P24UnitDropdownPage;
  let rulesAndActionsButtonPage: RulesAndActionsButtonPage;
  let rulesAndActionsPage: RulesAndActionsPage;
  let saveAndPublishButtonPage: SaveAndPublishButtonPage;
  let spinnerPage: SpinnerPage;
  let statusInactive2Page: StatusInactive2Page;
  let statusInactivePage: StatusInactivePage;

  test.beforeEach(async ({ page }) => {
    vars = {};
    chaseFieldNamePage = new ChaseFieldNamePage(page);
    correspondentPortalPage = new CorrespondentPortalPage(page);
    duplicatecopyButtonPage = new DuplicatecopyButtonPage(page);
    enumerationMappingButtonPage = new EnumerationMappingButtonPage(page);
    exitButtonPage = new ExitButtonPage(page);
    importRulePage = new ImportRulePage(page);
    mapHeadersButtonPage = new MapHeadersButtonPage(page);
    p1MoreButtonPage = new P1MoreButtonPage(page);
    p24UnitDropdownPage = new P24UnitDropdownPage(page);
    rulesAndActionsButtonPage = new RulesAndActionsButtonPage(page);
    rulesAndActionsPage = new RulesAndActionsPage(page);
    saveAndPublishButtonPage = new SaveAndPublishButtonPage(page);
    spinnerPage = new SpinnerPage(page);
    statusInactive2Page = new StatusInactive2Page(page);
    statusInactivePage = new StatusInactivePage(page);
  });

  test('REG_TS12_TC01_Verify that the user can import a rule from the required bid map.', async ({ page }) => {
    await stepGroups.stepGroup_Login_to_CORR_Portal(page, vars);
    await stepGroups.stepGroup_Smart_Mapper_from_Off_to_On(page, vars);
    await stepGroups.stepGroup_Creation_Of_Bid_Map_Upto_Header_Mapping(page, vars);
    // Write to test data profile: "Import Rule" = vars["Create New Maps"]
    await expect(correspondentPortalPage.Rules_and_Actions_Step_4_of_4).toBeVisible();
    await enumerationMappingButtonPage.Enumeration_Mapping_Button.click();
    await correspondentPortalPage.Heading_Save_and_Move_to_Next_Page1.waitFor({ state: 'visible' });
    await correspondentPortalPage.Yes_Proceed_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await expect(correspondentPortalPage.Rules_and_Actions_Step_4_of_4).toBeVisible();
    await rulesAndActionsButtonPage.Rules_and_Actions_Button.click();
    await correspondentPortalPage.Heading_Save_and_Move_to_Next_Page1.waitFor({ state: 'visible' });
    await stepGroups.stepGroup_IF_Condition_for_Yes_Proceed_Button(page, vars);
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await stepGroups.stepGroup_Adding_Rules_In_Rules_and_Actions_Screen(page, vars);
    await stepGroups.stepGroup_Add_Actions_in_Rules_and_Actions(page, vars);
    await duplicatecopyButtonPage.DuplicateCopy_Button.click();
    await expect(correspondentPortalPage.Rules_and_Actions_Step_4_of_4).toBeVisible();
    await correspondentPortalPage.Enter_a_Rule_Name_Field.fill(Array.from({length: 1}, () => "a".charAt(Math.floor(Math.random() * 1))).join(''));
    vars["ActiveRuleName"] = await correspondentPortalPage.Enter_a_Rule_Name_Field.inputValue() || '';
    vars["WhenBidFieldEnum"] = await statusInactivePage.When_Bid_Field_Enumeration_Mapping.textContent() || '';
    await expect(statusInactivePage.When_Bid_Field_Enumeration_Mapping).toContainText(vars["WhenBidFieldEnum"]);
    await expect(chaseFieldNamePage.When_Bid_Field).toBeVisible();
    await expect(statusInactivePage.Bid_Enumeration_TapeValue).toBeVisible();
    await expect(statusInactivePage.Chase_Field_Name_2).toBeVisible();
    await expect(p1MoreButtonPage.Chase_Value).toBeVisible();
    vars["First Active Rule Name"] = await rulesAndActionsPage.First_Rule_Name_Field.inputValue() || '';
    vars["First Active Rule Multiselected Value"] = await importRulePage.First_Active_Rule_Multiselected_Value.textContent() || '';
    vars["Bid Field Selected Option From Active 1st Rule"] = await importRulePage.Bid_Field_Selected_Option_From_Active_1st_Rule.textContent() || '';
    vars[" Bid Enumerated Tape Value Selected Option From Active 1st Rule"] = await importRulePage.Bid_Enumerated_Tape_Value_Selected_Option_From_Active_1st_Rule.textContent() || '';
    vars["Chase Field Name Selected Option From Active 1st Rule"] = await importRulePage.Chase_Field_Name_Selected_Option_From_Active_1st_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["Chase Value Selected Option From Active 1st Rule"] = await importRulePage.Chase_Value_Selected_Option_From_Active_1st_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["Second Active Rule Name"] = await statusInactive2Page.Rule_Name.inputValue() || '';
    vars["Second Active Rule Multiselected Value"] = await rulesAndActionsPage.Select_Category_DropdownDuplicated.textContent() || '';
    vars["Bid Field Selected Option From Active 2nd Rule"] = await importRulePage.Bid_Field_Selected_Option_From_Active_2nd_Rule.textContent() || '';
    vars[" Bid Enumerated Tape Value Selected Option From Active 2nd Rule"] = await importRulePage.Bid_Enumerated_Tape_Value_Selected_Option_From_Active_2nd_Rule.textContent() || '';
    vars["Chase Field Name Selected Option From Active 2nd Rule"] = await importRulePage.Chase_Field_Name_Selected_Option_From_Active_2nd_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["Chase Value Selected Option From Active 2nd Rule"] = await importRulePage.Chase_Value_Selected_Option_From_Active_2nd_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    await saveAndPublishButtonPage.Save_and_Publish_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    vars["Version"] = await correspondentPortalPage.Version.textContent() || '';
    await expect(correspondentPortalPage.Version).toContainText(vars["Version"]);
    await correspondentPortalPage.Bid_Maps_name.click();
    await mapHeadersButtonPage.Map_Headers_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await enumerationMappingButtonPage.Enumeration_Mapping_Button.click();
    await expect(correspondentPortalPage.You_have_unidentified_fields_do_you_want_to_proceed_Further).toBeVisible();
    await correspondentPortalPage.Yes_Proceed_Button.click();
    await rulesAndActionsButtonPage.Rules_and_Actions_Button.click();
    await expect(correspondentPortalPage.You_have_unidentified_fields_do_you_want_to_proceed_Further).toBeVisible();
    await correspondentPortalPage.Yes_Proceed_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await duplicatecopyButtonPage.DuplicateCopy_Button.click();
    await statusInactive2Page.Rule_Name.scrollIntoViewIfNeeded();
    await statusInactivePage.Enter_Rule_Name.fill(Array.from({length: 1}, () => "A".charAt(Math.floor(Math.random() * 1))).join(''));
    vars["Rule_Name"] = await statusInactivePage.Enter_Rule_Name.inputValue() || '';
    await expect(statusInactive2Page.When_Bid_Field_Rules_and_Actions).toBeVisible();
    await expect(statusInactivePage.When_Bid_Field_2).toBeVisible();
    await expect(p1MoreButtonPage.Bid_Enumerated_Tape_Value).toBeVisible();
    await expect(statusInactivePage.Chase_Field_Name).toBeVisible();
    await expect(p24UnitDropdownPage.ChaseValue).toBeVisible();
    vars["Draft Rule Name"] = await statusInactivePage.Enter_Rule_Name.inputValue() || '';
    vars["Draft Rule Multiselected Value"] = await importRulePage.Draft_Rule_Multiselected_Value.textContent() || '';
    vars["Bid Field Selected Option From Draft Rule"] = await importRulePage.Bid_Field_Selected_Option_From_Draft_Rule.textContent() || '';
    vars[" Bid Enumerated Tape Value Selected Option From Draft Rule"] = await importRulePage.Bid_Enumerated_Tape_Value_Selected_Option_From_Draft_Rule.textContent() || '';
    vars["Chase Field Name Selected Option From Draft Rule"] = await importRulePage.Chase_Field_Name_Selected_Option_From_Draft_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["Chase Value Selected Option From Draft Rule"] = await importRulePage.Chase_Value_Selected_Option_From_Draft_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    await correspondentPortalPage.Save_Draft_Button1.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await exitButtonPage.Exit_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    vars["StatusInListScreen"] = await p1MoreButtonPage.Status_In_BidMap_Listcreen.textContent() || '';
    await expect(p1MoreButtonPage.Status_In_BidMap_Listcreen).toContainText(vars["StatusInListScreen"]);
  });
});
