// [PREREQ-APPLIED]
// [POM-APPLIED]
import { test, expect } from '@playwright/test';
import path from 'path';
import * as stepGroups from '../../../src/helpers/step-groups';
import { ActionruleheaderPage } from '../../../src/pages/correspondant/actionruleheader';
import { CorrespondentPortalPage } from '../../../src/pages/correspondant/correspondent-portal';
import { EnumerationMappingButtonPage } from '../../../src/pages/correspondant/enumeration-mapping-button';
import { ImportRulePage } from '../../../src/pages/correspondant/import-rule';
import { P15Active2Page } from '../../../src/pages/correspondant/p-15-active-2';
import { RulesAndActionsButtonPage } from '../../../src/pages/correspondant/rules-and-actions-button';
import { RulesAndActionsPage } from '../../../src/pages/correspondant/rules-and-actions';
import { SpinnerPage } from '../../../src/pages/correspondant/spinner';
import { StatusInactive2Page } from '../../../src/pages/correspondant/status-inactive--2';
import { StatusInactivePage } from '../../../src/pages/correspondant/status-inactive-';
import { runPrereq_788 } from '../../../src/helpers/prereqs/prereq-788';

test.describe('REG_Bid Maps', () => {
  let vars: Record<string, string> = {};
  let actionruleheaderPage: ActionruleheaderPage;
  let correspondentPortalPage: CorrespondentPortalPage;
  let enumerationMappingButtonPage: EnumerationMappingButtonPage;
  let importRulePage: ImportRulePage;
  let p15Active2Page: P15Active2Page;
  let rulesAndActionsButtonPage: RulesAndActionsButtonPage;
  let rulesAndActionsPage: RulesAndActionsPage;
  let spinnerPage: SpinnerPage;
  let statusInactive2Page: StatusInactive2Page;
  let statusInactivePage: StatusInactivePage;

  test.beforeEach(async ({ page }) => {
    vars = {};
    await runPrereq_788(page, vars);
    actionruleheaderPage = new ActionruleheaderPage(page);
    correspondentPortalPage = new CorrespondentPortalPage(page);
    enumerationMappingButtonPage = new EnumerationMappingButtonPage(page);
    importRulePage = new ImportRulePage(page);
    p15Active2Page = new P15Active2Page(page);
    rulesAndActionsButtonPage = new RulesAndActionsButtonPage(page);
    rulesAndActionsPage = new RulesAndActionsPage(page);
    spinnerPage = new SpinnerPage(page);
    statusInactive2Page = new StatusInactive2Page(page);
    statusInactivePage = new StatusInactivePage(page);
  });

  test('REG_TS12_TC02_Verify that the user can import a rule from the required bid map.', async ({ page }) => {

    await stepGroups.stepGroup_Creation_Of_Bid_Map_Upto_Header_Mapping(page, vars);
    await enumerationMappingButtonPage.Enumeration_Mapping_Button.click();
    await correspondentPortalPage.Heading_Save_and_Move_to_Next_Page1.waitFor({ state: 'visible' });
    await correspondentPortalPage.Yes_Proceed_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await rulesAndActionsButtonPage.Rules_and_Actions_Button.click();
    await expect(correspondentPortalPage.You_have_unidentified_fields_do_you_want_to_proceed_Further).toBeVisible();
    await correspondentPortalPage.Yes_Proceed_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await correspondentPortalPage.Import_Rule_Button.click();
    vars["Bid Map Keyword"] = String(vars["Create New Maps"]).split("_")["1"] || '';
    await statusInactive2Page.Search_Map_EnumerationMapping.fill(vars["Bid Map Keyword"]);
    await importRulePage.Searching.waitFor({ state: 'hidden' });
    await importRulePage.Keyword_Related_Maps.waitFor({ state: 'visible' });
    await statusInactive2Page.Search_Map_EnumerationMapping.clear();
    await statusInactive2Page.Search_Map_EnumerationMapping.fill(vars["Create New Maps"]);
    await importRulePage.Searching.waitFor({ state: 'hidden' });
    await statusInactive2Page.Import_Rule_dropdown.click();
    await page.getByText(vars["First Active Rule Name"]).waitFor({ state: 'visible' });
    await expect(page.getByText(vars["Second Active Rule Name"])).toBeVisible();
    await expect(page.getByText(vars["Draft Rule Name"])).not.toBeVisible();
    await statusInactive2Page.Search_Field_ImportRule.clear();
    await statusInactive2Page.Search_Field_ImportRule.fill(vars["Draft Rule Name"]);
    await importRulePage.No_Result_Message.waitFor({ state: 'visible' });
    await statusInactive2Page.Search_Field_ImportRule.clear();
    await statusInactive2Page.Search_Field_ImportRule.fill(vars["First Active Rule Name"]);
    await page.getByText(vars["First Active Rule Name"]).waitFor({ state: 'visible' });
    await statusInactive2Page.Search_Field_ImportRule.clear();
    await statusInactive2Page.Search_Field_ImportRule.fill(vars["Second Active Rule Name"]);
    await page.getByText(vars["Second Active Rule Name"]).waitFor({ state: 'visible' });
    await statusInactive2Page.Search_Field_ImportRule.clear();
    await page.waitForLoadState('networkidle');
    await expect(importRulePage.Disabled_Apply_Selected_Button).toBeVisible();
    await importRulePage.First_Active_Rule_Checkbox.check();
    await expect(importRulePage.Disabled_Apply_Selected_Button).toBeVisible();
    await expect(importRulePage.Apply_Selected_Button).toBeVisible();
    vars["Apply Selected Count"] = await importRulePage.Apply_Selected_Count.textContent() || '';
    expect(String(vars["Apply Selected Count"])).toBe("1");
    await importRulePage.Second_Active_Rule_Checkbox.check();
    vars["Apply Selected Count"] = await importRulePage.Apply_Selected_Count.textContent() || '';
    expect(String(vars["Apply Selected Count"])).toBe("2");
    await p15Active2Page.Apply_Selected_Button.click();
    await actionruleheaderPage.Rules_and_Actions_Heading.waitFor({ state: 'visible' });
    await expect(rulesAndActionsPage.First_Rule_Name_Field).toHaveValue(vars["First Active Rule Name"]);
    vars["First Active Rule Multiselected Value from 2nd BidMp"] = await importRulePage.First_Active_Rule_Multiselected_Value.textContent() || '';
    vars["First Active Rule Multiselected Value from 2nd BidMp"] = String(vars["First Active Rule Multiselected Value from 2nd BidMp"]).trim();
    vars["First Active Rule Multiselected Value"] = String(vars["First Active Rule Multiselected Value"]).trim();
    expect(String(vars["First Active Rule Multiselected Value"])).toBe(vars["First Active Rule Multiselected Value from 2nd BidMp"]);
    vars["Bid Field Selected Option From Active 1st Rule from 2nd BidMap"] = await importRulePage.Bid_Field_Selected_Option_From_Active_1st_Rule.textContent() || '';
    vars["Bid Field Selected Option From Active 1st Rule from 2nd BidMap"] = String(vars["Bid Field Selected Option From Active 1st Rule from 2nd BidMap"]).trim();
    vars["Bid Field Selected Option From Active 1st Rule"] = String(vars["Bid Field Selected Option From Active 1st Rule"]).trim();
    expect(String(vars["Bid Field Selected Option From Active 1st Rule"])).toBe(vars["Bid Field Selected Option From Active 1st Rule from 2nd BidMap"]);
    vars[" Bid Enumerated Tape Value Selected Option From Active 1st Rule from 2nd BidMap"] = await importRulePage.Bid_Enumerated_Tape_Value_Selected_Option_From_Active_1st_Rule.textContent() || '';
    vars["Bid Enumerated Tape Value Selected Option From Active 1st Rule"] = String(vars[" Bid Enumerated Tape Value Selected Option From Active 1st Rule"]).trim();
    vars["Bid Enumerated Tape Value Selected Option From Active 1st Rule from 2nd BidMap"] = String(vars[" Bid Enumerated Tape Value Selected Option From Active 1st Rule from 2nd BidMap"]).trim();
    expect(String(vars["Bid Enumerated Tape Value Selected Option From Active 1st Rule"])).toBe(vars["Bid Enumerated Tape Value Selected Option From Active 1st Rule from 2nd BidMap"]);
    vars["Chase Field Name Selected Option From Active 1st Rule from 2nd BidMap"] = await importRulePage.Chase_Field_Name_Selected_Option_From_Active_1st_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["Chase Field Name Selected Option From Active 1st Rule from 2nd BidMap"] = String(vars["Chase Field Name Selected Option From Active 1st Rule from 2nd BidMap"]).trim();
    vars["Chase Field Name Selected Option From Active 1st Rule"] = String(vars["Chase Field Name Selected Option From Active 1st Rule"]).trim();
    expect(String(vars["Chase Field Name Selected Option From Active 1st Rule"])).toBe(vars["Chase Field Name Selected Option From Active 1st Rule from 2nd BidMap"]);
    vars["Chase Value Selected Option From Active 1st Rule from 2nd BidMap"] = await importRulePage.Chase_Value_Selected_Option_From_Active_1st_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["Chase Value Selected Option From Active 1st Rule from 2nd BidMap"] = String(vars["Chase Value Selected Option From Active 1st Rule from 2nd BidMap"]).trim();
    vars["Chase Value Selected Option From Active 1st Rule"] = String(vars["Chase Value Selected Option From Active 1st Rule"]).trim();
    await expect(statusInactive2Page.Rule_Name).toHaveValue(vars["Second Active Rule Name"]);
    vars["Second Active Rule Multiselected Value from 2nd Bid Map"] = await rulesAndActionsPage.Select_Category_DropdownDuplicated.textContent() || '';
    vars["Second Active Rule Multiselected Value from 2nd Bid Map"] = String(vars["Second Active Rule Multiselected Value from 2nd Bid Map"]).trim();
    vars["Second Active Rule Multiselected Value"] = String(vars["Second Active Rule Multiselected Value"]).trim();
    expect(String(vars["Second Active Rule Multiselected Value from 2nd Bid Map"])).toBe(vars["Second Active Rule Multiselected Value"]);
    vars["Bid Field Selected Option From Active 2nd Rule from 2nd BidMap"] = await importRulePage.Bid_Field_Selected_Option_From_Active_2nd_Rule.textContent() || '';
    vars["Bid Field Selected Option From Active 2nd Rule from 2nd BidMap"] = String(vars["Bid Field Selected Option From Active 2nd Rule from 2nd BidMap"]).trim();
    vars["Bid Field Selected Option From Active 2nd Rule"] = String(vars["Bid Field Selected Option From Active 2nd Rule"]).trim();
    expect(String(vars["Bid Field Selected Option From Active 2nd Rule from 2nd BidMap"])).toBe(vars["Bid Field Selected Option From Active 2nd Rule"]);
    vars["Bid Enumerated Tape Value Selected Option From Active 2nd Rule"] = String(vars[" Bid Enumerated Tape Value Selected Option From Active 2nd Rule"]).trim();
    vars["Bid Enumerated Tape Value Selected Option From Active 2nd Rule from 2nd Bid Map"] = await importRulePage.Bid_Enumerated_Tape_Value_Selected_Option_From_Active_2nd_Rule.textContent() || '';
    vars["Bid Enumerated Tape Value Selected Option From Active 2nd Rule from 2nd Bid Map"] = String(vars["Bid Enumerated Tape Value Selected Option From Active 2nd Rule from 2nd Bid Map"]).trim();
    expect(String(vars["Bid Enumerated Tape Value Selected Option From Active 2nd Rule"])).toBe(vars["Bid Enumerated Tape Value Selected Option From Active 2nd Rule from 2nd Bid Map"]);
    vars["Chase Field Name Selected Option From Active 2nd Rule from 2nd BidMap"] = await importRulePage.Chase_Field_Name_Selected_Option_From_Active_2nd_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["Chase Field Name Selected Option From Active 2nd Rule from 2nd BidMap"] = String(vars["Chase Field Name Selected Option From Active 2nd Rule from 2nd BidMap"]).trim();
    vars["Chase Field Name Selected Option From Active 2nd Rule"] = String(vars["Chase Field Name Selected Option From Active 2nd Rule"]).trim();
    expect(String(vars["Chase Field Name Selected Option From Active 2nd Rule from 2nd BidMap"])).toBe(vars["Chase Field Name Selected Option From Active 2nd Rule"]);
    vars["Chase Value Selected Option From Active 2nd Rule from 2nd BidMap"] = await importRulePage.Chase_Value_Selected_Option_From_Active_2nd_Rule.evaluate(el => { const s = el as HTMLSelectElement; return s.options[s.selectedIndex]?.text || ''; });
    vars["Chase Value Selected Option From Active 2nd Rule from 2nd BidMap"] = String(vars["Chase Value Selected Option From Active 2nd Rule from 2nd BidMap"]).trim();
    vars["Chase Value Selected Option From Active 2nd Rule"] = String(vars["Chase Value Selected Option From Active 2nd Rule"]).trim();
    expect(String(vars["Chase Value Selected Option From Active 2nd Rule from 2nd BidMap"])).toBe(vars["Chase Value Selected Option From Active 2nd Rule"]);
    await expect(statusInactivePage.Enter_Rule_Name).toBeVisible();
    await expect(importRulePage.Draft_Rule_Multiselected_Value).toBeVisible();
    await expect(importRulePage.Bid_Field_Selected_Option_From_Draft_Rule).toBeVisible();
    await expect(importRulePage.Bid_Enumerated_Tape_Value_Selected_Option_From_Draft_Rule).toBeVisible();
    await expect(importRulePage.Chase_Field_Name_Selected_Option_From_Draft_Rule).toBeVisible();
    await expect(importRulePage.Chase_Value_Selected_Option_From_Draft_Rule).toBeVisible();
  });
});
