require("dotenv").config({ path: require("path").join(__dirname, "../.env.example") });
 
const path = require("path");
const nodemailer = require("nodemailer");
const { generateReport } = require("./generate-report");
 
function getProjectName() {
    if (process.env.PROJECT_NAME) return process.env.PROJECT_NAME;
    try {
        const pkg = require(path.join(__dirname, "../package.json"));
        return pkg.name || "project";
    } catch {
        return "project";
    }
}
 
/**
 @param {boolean} manualTrigger
 */
async function sendEmail(manualTrigger = true) {
    const projectName = getProjectName();
 
    try {
        const { zipFileName, zipPath } = await generateReport(projectName);
 
        if (!manualTrigger) {
            return;
        }
 
        const { EMAIL_USER, EMAIL_PASS, EMAIL_TO } = process.env;
        if (!EMAIL_USER || !EMAIL_PASS || !EMAIL_TO) {
            throw new Error(
                "Missing email credentials in .env — ensure EMAIL_USER, EMAIL_PASS, and EMAIL_TO are set."
            );
        }
 
        const readableTimestamp = new Date().toLocaleString("en-IN", {
            timeZone: "Asia/Kolkata",
            dateStyle: "full",
            timeStyle: "medium",
        });
 
        const transporter = nodemailer.createTransport({
            service: "gmail",
            auth: {
                user: EMAIL_USER,
                pass: EMAIL_PASS,
            },
        });
 
        const subject = `[QA Automation] Playwright ${projectName} Execution Report`;
 
        const htmlBody = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background: #1a1a2e; color: #fff; padding: 20px 24px;">
          <h2 style="margin: 0;">🎭 Playwright Execution Report</h2>
        </div>
        <div style="padding: 24px;">
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr>
              <td style="padding: 8px 0; color: #555; width: 140px;"><strong>Project</strong></td>
              <td style="padding: 8px 0;">${projectName}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #555;"><strong>Executed At</strong></td>
              <td style="padding: 8px 0;">${readableTimestamp}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #555;"><strong>Report File</strong></td>
              <td style="padding: 8px 0;"><code style="background:#f4f4f4; padding:2px 6px; border-radius:4px;">${zipFileName}</code></td>
            </tr>
          </table>
          <hr style="border:none; border-top:1px solid #eee; margin:20px 0;" />
          <p style="font-size:14px; color:#333;">
            Please find the <strong>Playwright HTML Report</strong> attached.<br/>
            Extract the ZIP and open <code>index.html</code> in any browser to view full results.
          </p>
          <p style="font-size:12px; color:#999; margin-top:24px;">
            Auto-generated by QA Automation Framework. Do not reply.
          </p>
        </div>
      </div>
    `;
 
        await transporter.sendMail({
            from: `"QA Team" <${EMAIL_USER}>`,
            to: EMAIL_TO,
            subject,
            html: htmlBody,
            attachments: [{ filename: zipFileName, path: zipPath }],
        });
        console.log("Email Sent Successfully..")
 
    } catch (error) {
        console.error("\n send-email.js failed:", error.message || error);
        process.exit(1);
    }
}
 
module.exports = sendEmail;
 
if (require.main === module) {
    sendEmail(true);
}