export const APP_CONSTANTS = {
  ASIA_KOLKATA: "Asia/Kolkata",
  AMERICA_NEW_YORK: "America/New_York",
  UTC: "UTC",
  PATH_DATEFORMAT: "dd-MM-yyyy HH-mm-ss",
  HEADERSUI: "Comm. Loans and Comm. Amount and Amt. Delivered",
  HEADERSUI1: "Comm. Date and Closed Date and Expiration Date",
  INDIVIDUAL_HEADERS_COMMITMENTLIST: "Loan Amount and Ref Sec Price and Gross Price and Hedge Ratio and Curr Market Value and Curr Gross and Chase Loan#",
  LOAN_AMOUNT: "Loan Amount",
  MARK_ADJ: "Mark Adj",
  HEADERSUI_PRICEOFFERD: "#Loans / #Errors and Bid Value",
  ThreeDigitBidReqID: "878",
  DATE_FORMAT_DMYYYY: "d-M-yyyy",
  BID_REQ_ID: "Bid Req. ID",
  DATE_FORMAT_MMDDYYYY: "MM/dd/yyyy",
  MONTH_FORMAT: "MMM",
  MONTH_NUM_FORMAT: "MM",
  SATURDAY: "Saturday",
  SUNDAY: "Sunday",
  ZERO_WITH_DOLLAR_SYMBOL: "$0",
  NINE: "9",
  ONE: "1",
  TWO: "2",
  FIFTEEN: "15",
  THIRTEEN: "13",
  FIVE: "5",
  THREE: "3",
  DOLLAR_SYMBOL: "$",
  PERCENTAGE_SYMBOL: "%",
  PQ_PR: "| PQ | PS",
  LOANAMOUNT_HEADER_EXCEL: "LoanAmt",
  CURRENTMARKETVALUE: "CurrentMarketValue",
  BIDREQUESTNUMBER_METAINFO: "BID REQUEST NUMBER",
  COMMITORDERNUMBER_METAINFO: "COMMIT ORDER NUMBER",
  REPORTGENERATIONTIME_METAINFO: "REPORT GENERATION TIME",
  DATE_TIME_FORMAT_EXCEL_EST: "MM/dd/yyyy HH:mm",
  ZERO: "0",
  PRICEOFFERED_STATUS: "Price Offered",
  PARTIALLYCOMMITTED_STATUS: "Partially Committed",
  EXPIRED_STATUS: "Expired",
  COMMITTED_STATUS: "Committed",
  COMMITMENT_IN_PROGRESS_STATUS: "Commitment in progress",
  HEADER_NAME_UI_LOANAMOUNT: "LoanAmount",
  PRICING_REQUEST: "pricing-request",
  PRICING_RESPONSE: "pricing-response",
  SOURCE_LOAN_NUMBER: 'sourceLoanNumber":',
  CORR_LOAN_NUMBER: 'corrLoanNumber":',
  CORR_CODE: 'corrCode":',
  REF_SEC_NAME: 'referenceSecurityName":',
  REF_SEC_PRICE: 'referenceSecurityPrice":',
  REF_SEC_MONTH: '"referenceSecurityMonth":',
  INVALID_SEARCH_INPUT: "ABCD1234",
  NO_RESULT_TEXT: "No result",
  COMMITMENT_ID_LENGTH: "8",
  LOANS_FAILED_TO_ADD: "Loans failed to be added to commitment",
  DUPLICATE_LOAN: "is a Duplicate loan. It is already committed",
  LOANS_ADDED_SUCCESSFULLY: "Loans added successfully -",
  DATE_TIME_FORMAT_COMMIT: "M/d/yy h:mm a",
  FILTER_COMPANY_NAME_AMERICA: "American",
  DATE_FORMAT_YYYYMMDD: "yyyy/MM/dd",
  DUPLICATE_TEXT_POPUP: 'is a Duplicate loan. It is already committed',
  TIME_FORMAT_HHMMA: 'hh:mma',
  DATE_FORMAT_MDYY: "M/d/yy",
  DATE_FORMAT_DDMMYYYY: "dd-MM-yyyy",
  TIME_FORMAT1_HHMMA: "hh:mm a",
  TIME_FORMAT_HMMA: "h:mm a",
  BID_REQUEST_HEADER: "BidReq.ID",
  BID_REQUEST_HEADER_EXCEL: "BidRequestID",
  EXECUTIONTYPE_HEADER_UI: "ExecutionType",
  ET: "ET",
  STATUS: "Status",
  DATE_TEXT: "Date:",
  COMPANY_TEXT: "Company:",
  ELEVEN: "11",
  LOAN_TEXT: "Loan",
  MARKET_ADJ_ERROR_TEXT: "can not be committed. Market adjuster value",
  MARKET_ADJ_REASON_TEXT: "is greater than market threshold value",
  ONE_HUNDRED_TWEENTY: "120",
  STANDARD_TEXT: "Standard",
  ACTIVE: "ACTIVE",
  DATE_FORMAT_SLASH: "dd/MM/yyyy/HH:mm:ss",
  EXECUTION_TYPE_STANDARD: "STANDARD",
  MONTH_FORMAT_SLASH: "MM/dd/yyyy/HH:mm:ss",
  Testsigma_: "Testsigma_",
  Hii: "Hii",
  Hey: "hey",
  LOAN_PURPOSE: "Loan Purpose",
  ThreeDigitBidID: "874",
  DATE_FORMAT: "d-M-yyyy",
  DATE_FORMATE_: "MM/dd/yyyy",
  TIME_FORMATE: "h:mm a",
  SAMPLE: "sample",
  ZEROWITHDOLLER: "$0",
  TEN: "10",
  PRICEOFFERED: "Price Offered",
  PARTIALLYCOMMITTED: "Partially Committed",
  EXPIRED: "Expired",
  COMMITTED: "Committed",
  COMMITMENT_IN_PROGRESS: "Commitment in progress"
};


 
  TIME_FORMAT_HMMA:"h:mm a",
  BID_REQUEST_HEADER:"BidReq.ID",
  BID_REQUEST_HEADER_EXCEL:"BidRequestID",
  EXECUTIONTYPE_HEADER_UI:"ExecutionType",
  ET:'ET',
  STATUS:"Status",
  DATE_TEXT:"Date:",
  COMPANY_TEXT:"Company:",
  ELEVEN:'11',
  LOAN_TEXT:"Loan",
  MARKET_ADJ_ERROR_TEXT:"can not be committed. Market adjuster value",
  MARKET_ADJ_REASON_TEXT:"is greater than market threshold value",
  ONE_HUNDRED_TWEENTY:'120',
  STANDARD_TEXT:"Standard",
  ADD_TO_COMMIT_TEXT:'Add to Commit',
};