export const APP_CONSTANTS = {
  ASIA_KOLKATA: "Asia/Kolkata",
  America_New_York:"America/New_York",
  UTC:"UTC",
  PATH_DATEFORMAT:"dd-MM-yyyy HH-mm-ss",
  HeadersUI:"Comm. Loans and Comm. Amount and Amt. Delivered",
  HeadersUI1:"Comm. Date and Closed Date and Expiration Date",
  IndividualHeadersCommitmentList:"Loan Amount and Ref Sec Price and Gross Price and Hedge Ratio and Curr Market Value and Curr Gross and Chase Loan#",
  LoanAmount:"Loan Amount",
  MarkAdj:"Mark Adj",
  HeadersUi:"#Loans / #Errors and Bid Value",
  ThreeDigitBidReqID:"878",
  DATE_FORMAT:"d-M-yyyy",
  BID_REQ_ID:"Bid Req. ID",
  DATE_FORMATE_:"MM/dd/yyyy",
  TIME_FORMATE:"h:mm a",
  SATURDAY:"Saturday",
  SUNDAY:"Sunday",
  ZEROWITHDOLLER:"$0",
  NINE:"9",
  ONE:"1",
  TWO:"2",
  FIFTEEN:"15",
  THIRTEEN:"13",
  FIVE:"5",
  THREE:"3",
  DOLLAR_SYMBOL:"$",
  PERCENTAGE_SYMBOL:"%",
  PQ_PR:"| PQ | PS",
  LOANAMOUNT_HEADER_EXCEL:"LoanAmt",
  CURRENTMARKETVALUE:"CurrentMarketValue",
  BIDREQUESTNUMBER_METAINFO:"BID REQUEST NUMBER",
  COMMITORDERNUMBER_METAINFO:"COMMIT ORDER NUMBER",
  REPORTGENERATIONTIME_METAINFO:"REPORT GENERATION TIME",
  DATE_TIME_FORMAT_EXCEL_EST:"MM/dd/yyyy HH:mm",
  ZERO:"0",
  PRICEOFFERED:"Price Offered",
 PARTIALLYCOMMITTED:"Partially Committed",
 EXPIRED:"Expired",
 COMMITTED:"Committed",
};