// [PREREQ-APPLIED]
// [POM-APPLIED]
import { test, expect } from '@playwright/test';
import path from 'path';
import * as stepGroups from '../../../src/helpers/step-groups';
import { BidRequestsPage } from '../../../src/pages/correspondant/bid-requests';
import { CommitmentListPage } from '../../../src/pages/correspondant/commitment-list';
import { CorrespondentPortalPage } from '../../../src/pages/correspondant/correspondent-portal';
import { PriceOfferedPage } from '../../../src/pages/correspondant/price-offered';
import { SpinnerPage } from '../../../src/pages/correspondant/spinner';
import { runPrereq_1746 } from '../../../src/helpers/prereqs/prereq-1746';

test.describe('Unassigned', () => {
  let vars: Record<string, string> = {};
  let bidRequestsPage: BidRequestsPage;
  let commitmentListPage: CommitmentListPage;
  let correspondentPortalPage: CorrespondentPortalPage;
  let priceOfferedPage: PriceOfferedPage;
  let spinnerPage: SpinnerPage;

  test.beforeEach(async ({ page }) => {
    vars = {};
    await runPrereq_1746(page, vars);
    bidRequestsPage = new BidRequestsPage(page);
    commitmentListPage = new CommitmentListPage(page);
    correspondentPortalPage = new CorrespondentPortalPage(page);
    priceOfferedPage = new PriceOfferedPage(page);
    spinnerPage = new SpinnerPage(page);
  });

  test('REG_TS04_TC03_If a bid contains multiple commitments, then the details screen should display the list of all those commitments.', async ({ page }) => {

    await correspondentPortalPage.Commitments_Side_Menu.click();
    await commitmentListPage.Committed_List_Dropdown.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await priceOfferedPage.Search_Dropdown.click();
    await priceOfferedPage.Search_Dropdown.clear();
    await priceOfferedPage.Search_Dropdown.fill(vars["BidReqId"]);
    await priceOfferedPage.Bid_Request_ID_DropdownCommitment_List_Page.click();
    await commitmentListPage.Commitment_IDCommitment_List_Page.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    vars["FirstCommitOrderBefore"] = await commitmentListPage.Commit_OrderCommitment_List.textContent() || '';
    vars["FirstCommitIDBefore"] = await priceOfferedPage.Commit_IDCommitment_List.textContent() || '';
    vars["FirstCommitTimeBefore"] = await commitmentListPage.Commit_TimeCommitment_Screen.textContent() || '';
    vars["FirstMarketValueBefore"] = await commitmentListPage.Market_ValueCommitment_List.textContent() || '';
    vars["FirstCurrMarketValueBefore"] = await commitmentListPage.Current_Market_ValueCommitment_List.textContent() || '';
    vars["FirstLockedLastName"] = await priceOfferedPage.Locked_Last_NameCommitment_List.textContent() || '';
    vars["FirstLockedLoanAmount"] = await priceOfferedPage.Locked_Loan_AmountCommitment_List.textContent() || '';
    vars["FirstLockedRefSecProd"] = await priceOfferedPage.Locked_RefSecProdCommitment_List.textContent() || '';
    vars["FirstLockedRefSecPrice"] = await priceOfferedPage.Locked_RefSecPriceCommitment_List.textContent() || '';
    vars["FirstLockedGrossPrice"] = await priceOfferedPage.Locked_GrossPriceCommitment_List.textContent() || '';
    vars["FirstLockedHedgeRatio"] = await priceOfferedPage.Locked_Hedge_RatioCommitment_List.textContent() || '';
    vars["FirstLockedMarkAdj"] = await priceOfferedPage.Locked_MarkAdjCommitment_List.textContent() || '';
    vars["FirstLockedCurrGross"] = await priceOfferedPage.Locked_CurrGrossCommitment_List.textContent() || '';
    vars["SecondCommitOrder"] = await commitmentListPage.Second_Commit_OrderCommitment_List.textContent() || '';
    vars["SecondCommitID"] = await commitmentListPage.Second_Commit_IDCommitment_List.textContent() || '';
    vars["SecondCommitTime"] = await commitmentListPage.Second_Commit_Time.textContent() || '';
    vars["SecondMarketValue"] = await commitmentListPage.Market_ValueCommitment_List2.textContent() || '';
    vars["SecondCurrentMarketValue"] = await commitmentListPage.Second_Current_Market_Value.textContent() || '';
    await correspondentPortalPage.Commitments_Side_Menu.click();
    await correspondentPortalPage.Price_Offered_List_Dropdown.click();
    await bidRequestsPage.Search_by_Bid_Request_ID_Field.fill(vars["BidReqId"]);
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await priceOfferedPage.BidRequestIDPrice_Offered_New.click();
    await priceOfferedPage.Check_Bid_Loan_NumChase_Exe.waitFor({ state: 'visible' });
    await priceOfferedPage.Check_Bid_Loan_NumChase_Exe.check();
    await priceOfferedPage.Get_Price_Button.waitFor({ state: 'visible' });
    await priceOfferedPage.Get_Price_Button.click();
    await priceOfferedPage.Commit_Selected_1_Dropdown.waitFor({ state: 'visible' });
    await priceOfferedPage.Commit_Selected_1_Dropdown.click();
    await priceOfferedPage.Yes_Commit_ButtonPopup.click();
    vars["ThirdCommitTime"] = (() => {
      const d = new Date();
      const opts: Intl.DateTimeFormatOptions = { timeZone: "UTC" };
      const fmt = "h:mm a";
      // Map Java date format to Intl parts
      const parts = new Intl.DateTimeFormat('en-US', { ...opts, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true }).formatToParts(d);
      const p = Object.fromEntries(parts.map(({type, value}) => [type, value]));
      return fmt.replace('yyyy', p.year || '').replace('yy', (p.year||'').slice(-2)).replace('MM', p.month || '').replace('dd', p.day || '').replace('HH', String(d.getHours()).padStart(2,'0')).replace('hh', p.hour || '').replace('mm', p.minute || '').replace('ss', p.second || '').replace('a', p.dayPeriod || '').replace(/M(?!M)/g, String(parseInt(p.month||'0'))).replace(/d(?!d)/g, String(parseInt(p.day||'0'))).replace(/h(?!h)/g, String(parseInt(p.hour||'0')));
    })();
    await priceOfferedPage.Okay_ButtonPopup.waitFor({ state: 'visible' });
    vars["ThirdCommitmentID"] = await priceOfferedPage.Commitment_IdPrice_Offered.textContent() || '';
    await priceOfferedPage.Okay_ButtonPopup.click();
    await priceOfferedPage.All_Loans_Tabprice_offered_screen.click();
    vars["ThirdCurrentMarket"] = await priceOfferedPage.Current_Market_ValueDetails_Screen.textContent() || '';
    vars["ThirdCommittedCorrLoan"] = await commitmentListPage.Third_Committed_Corr_Loan.textContent() || '';
    vars["ThirdCommittedLastName"] = await commitmentListPage.Third_Committed_Last_Name.textContent() || '';
    vars["ThirdCommittedLoanAmount"] = await commitmentListPage.Third_Committed_Loan_Amount.textContent() || '';
    vars["ThirdCommittedRefSecProd"] = await commitmentListPage.Third_Committed_Ref_Sec_Prod.textContent() || '';
    vars["ThirdCommittedRefSecPrice"] = await commitmentListPage.Third_Committed_Ref_Sec_Price.textContent() || '';
    vars["ThirdCommittedGrossPrice"] = await commitmentListPage.Third_Committed_Gross_Price.textContent() || '';
    vars["ThirdCommittedHedgeRatio"] = await commitmentListPage.Third_Committed_Hedge_Ratio.textContent() || '';
    vars["ThirdCommittedMarkAdj"] = await commitmentListPage.Third_Committed_Mark_Adj.textContent() || '';
    vars["ThirdCommittedLoanCurrGross"] = await commitmentListPage.Third_Committed_Loan_Curr_Gross.textContent() || '';
    await correspondentPortalPage.Commitments_Side_Menu.click();
    await commitmentListPage.Committed_List_Dropdown.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await priceOfferedPage.Search_Dropdown.click();
    await priceOfferedPage.Search_Dropdown.fill(vars["BidReqId"]);
    await priceOfferedPage.Bid_Request_ID_DropdownCommitment_List_Page.click();
    await commitmentListPage.Commitment_IDCommitment_List_Page.click();
    await expect(commitmentListPage.Commit_OrderCommitment_List).toContainText(vars["FirstCommitOrderBefore"]);
    await expect(priceOfferedPage.Commit_IDCommitment_List).toContainText(vars["FirstCommitIDBefore"]);
    await expect(commitmentListPage.Commit_TimeCommitment_Screen).toContainText(vars["FirstCommitTimeBefore"]);
    await expect(commitmentListPage.Market_ValueCommitment_List).toContainText(vars["ThirdCurrentMarket"]);
    await expect(commitmentListPage.Current_Market_ValueCommitment_List).toContainText(vars["FirstCurrMarketValueBefore"]);
    await expect(priceOfferedPage.Locked_Last_NameCommitment_List).toContainText(vars["FirstLockedLastName"]);
    await expect(priceOfferedPage.Locked_Loan_AmountCommitment_List).toContainText(vars["FirstLockedLoanAmount"]);
    await expect(priceOfferedPage.Locked_RefSecProdCommitment_List).toContainText(vars["FirstLockedRefSecProd"]);
    await expect(priceOfferedPage.Locked_RefSecPriceCommitment_List).toContainText(vars["FirstLockedRefSecPrice"]);
    await expect(priceOfferedPage.Locked_GrossPriceCommitment_List).toContainText(vars["FirstLockedGrossPrice"]);
    await expect(priceOfferedPage.Locked_Hedge_RatioCommitment_List).toContainText(vars["FirstLockedHedgeRatio"]);
    await expect(priceOfferedPage.Locked_MarkAdjCommitment_List).toContainText(vars["FirstLockedMarkAdj"]);
    await expect(priceOfferedPage.Locked_CurrGrossCommitment_List).toContainText(vars["FirstLockedCurrGross"]);
    await expect(commitmentListPage.Second_Commit_OrderCommitment_List).toContainText(vars["SecondCommitOrder"]);
    await expect(commitmentListPage.Second_Commit_IDCommitment_List).toContainText(vars["SecondCommitID"]);
    await expect(commitmentListPage.Second_Commit_Time).toContainText(vars["SecondCommitTime"]);
    await expect(commitmentListPage.Market_ValueCommitment_List2).toContainText(vars["ThirdCurrentMarket"]);
    await expect(commitmentListPage.Second_Current_Market_Value).toContainText(vars["SecondCurrentMarketValue"]);
    await expect(page.getByText(vars["ThirdCommitmentID"])).toBeVisible();
    await expect(commitmentListPage.Third_Commit_Time_Screen).toContainText(vars["ThirdCommitTime"]);
    await expect(commitmentListPage.Third_Market_ValueCommitment_List).toContainText(vars["ThirdCurrentMarket"]);
    await expect(commitmentListPage.Third_Current_Market_Value).toContainText(vars["ThirdCurrentMarket"]);
    await expect(commitmentListPage.Third_Locked_Last_NameCommitment_List).toContainText(vars["ThirdCommittedLastName"]);
    await expect(commitmentListPage.Third_Locked_LoanAmountCommitment_List).toContainText(vars["ThirdCommittedLoanAmount"]);
    await expect(commitmentListPage.Third_Locked_RefSecProdCommitment_List).toContainText(vars["ThirdCommittedRefSecProd"]);
    await expect(commitmentListPage.Third_Locked_RefSecPriceCommitment_List).toContainText(vars["ThirdCommittedRefSecPrice"]);
    await expect(commitmentListPage.Third_Locked_GrossCommitment_List).toContainText(vars["ThirdCommittedGrossPrice"]);
    await expect(commitmentListPage.Third_Locked_HedgeRatioCommitment_List).toContainText(vars["ThirdCommittedHedgeRatio"]);
    await expect(commitmentListPage.Third_Locked_MarAdjCommitment_List).toContainText(vars["ThirdCommittedMarkAdj"]);
    await expect(commitmentListPage.Third_Locked_CurrGrossCommitment_List).toContainText(vars["ThirdCommittedLoanCurrGross"]);
  });
});
