// [POM-APPLIED]
import { test, expect } from '@playwright/test';
import path from 'path';
import * as stepGroups from '../../../src/helpers/step-groups';
import { CorrespondentPortalPage } from '../../../src/pages/correspondant/correspondent-portal';
import { Deepikaaugbidqa1csvButtonDivPage } from '../../../src/pages/correspondant/deepikaaugbidqa1csv-button-div';
import { FileFormatNotAllowedDeepikaaugbidqa1pdfPage } from '../../../src/pages/correspondant/file-format-not-allowed-deepikaaugbidqa1pdf';
import { HeaderMappingPage } from '../../../src/pages/correspondant/header-mapping';
import { HeadingCreateNewMapPage } from '../../../src/pages/correspondant/heading-create-new-map';
import { P2142530YrFreddieMacFixedDropdownPage } from '../../../src/pages/correspondant/p-2142530-yr-freddie-mac-fixed-dropdown';
import { SelectAllCheckboxPage } from '../../../src/pages/correspondant/select-all-checkbox';
import { SpinnerPage } from '../../../src/pages/correspondant/spinner';

test.describe('REG_Bid Maps', () => {
  let vars: Record<string, string> = {};
  let correspondentPortalPage: CorrespondentPortalPage;
  let deepikaaugbidqa1csvButtonDivPage: Deepikaaugbidqa1csvButtonDivPage;
  let fileFormatNotAllowedDeepikaaugbidqa1pdfPage: FileFormatNotAllowedDeepikaaugbidqa1pdfPage;
  let headerMappingPage: HeaderMappingPage;
  let headingCreateNewMapPage: HeadingCreateNewMapPage;
  let p2142530YrFreddieMacFixedDropdownPage: P2142530YrFreddieMacFixedDropdownPage;
  let selectAllCheckboxPage: SelectAllCheckboxPage;
  let spinnerPage: SpinnerPage;

  test.beforeEach(async ({ page }) => {
    vars = {};
    correspondentPortalPage = new CorrespondentPortalPage(page);
    deepikaaugbidqa1csvButtonDivPage = new Deepikaaugbidqa1csvButtonDivPage(page);
    fileFormatNotAllowedDeepikaaugbidqa1pdfPage = new FileFormatNotAllowedDeepikaaugbidqa1pdfPage(page);
    headerMappingPage = new HeaderMappingPage(page);
    headingCreateNewMapPage = new HeadingCreateNewMapPage(page);
    p2142530YrFreddieMacFixedDropdownPage = new P2142530YrFreddieMacFixedDropdownPage(page);
    selectAllCheckboxPage = new SelectAllCheckboxPage(page);
    spinnerPage = new SpinnerPage(page);
  });

  test('REG_TS01_TC05_Verify that user should be able to upload only \\\"xls, xIsx, csv and txt files and we should not allow the user to upload any other file if tried uploading then it should display the erro', async ({ page }) => {
    await stepGroups.stepGroup_Login_to_CORR_Portal(page, vars);
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await correspondentPortalPage.Administration_Menu.click();
    await correspondentPortalPage.Bid_Maps_Menu.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await correspondentPortalPage.Add_New_Mapping_Button.click();
    await expect(headingCreateNewMapPage.Create_New_Map).toBeVisible();
    vars["Create New Map"] = new Date().toLocaleDateString('en-US') /* format: dd/MM/yyyy/HH:mm:ss */;
    vars["Create New Map"] = "Testsigma_" + vars["Create New Map"];
    await correspondentPortalPage.Create_New_Map_Field.fill(vars["Create New Map"]);
    vars["BidMap"] = await correspondentPortalPage.Create_New_Map_Field.inputValue() || '';
    await correspondentPortalPage.Create_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await expect(p2142530YrFreddieMacFixedDropdownPage.Bid_Maps_Name).toContainText(vars["Create New Map"]);
    await correspondentPortalPage.Select_Companys_Dropdown.click();
    await expect(correspondentPortalPage.Apply_Selected).toBeVisible();
    vars["CompanyCount"] = String(await correspondentPortalPage.Companies_In_Dropdown.count());
    await selectAllCheckboxPage.Select_All_Checkbox.check();
    await expect(correspondentPortalPage.Apply_Selected_for_Bid_Maps).toContainText(vars["CompanyCount"]);
    await correspondentPortalPage.Apply_Selected.click();
    await expect(correspondentPortalPage.Dropdown_selection_2).toHaveValue('');
    await correspondentPortalPage.Upload_File.setInputFiles(path.resolve(__dirname, 'test-data', "Bid Maps File.xlsx"));
    await expect(deepikaaugbidqa1csvButtonDivPage.Delete_Button_in_Bid_Maps).toBeVisible();
    await deepikaaugbidqa1csvButtonDivPage.Delete_Button_in_Bid_Maps.click();
    await expect(correspondentPortalPage.close_pop_up_bid_request_details).toBeVisible();
    await expect(correspondentPortalPage.Are_you_sure_you_want_to_delete_fixed_from_enumeration).toBeVisible();
    await expect(correspondentPortalPage.Yes_Proceed_Button).toBeVisible();
    await correspondentPortalPage.Yes_Proceed_Button.click();
    await page.waitForLoadState('networkidle');
    await headerMappingPage.File_Input.setInputFiles(path.resolve(__dirname, 'test-data', "Bid Maps File CSV.csv"));
    await expect(deepikaaugbidqa1csvButtonDivPage.Delete_Button_in_Bid_Maps).toBeVisible();
    await deepikaaugbidqa1csvButtonDivPage.Delete_Button_in_Bid_Maps.click();
    await expect(correspondentPortalPage.Are_you_sure_you_want_to_delete_fixed_from_enumeration).toBeVisible();
    await correspondentPortalPage.close_pop_up_bid_request_details.click();
    await page.waitForLoadState('networkidle');
    await deepikaaugbidqa1csvButtonDivPage.Delete_Button_in_Bid_Maps.click();
    await expect(correspondentPortalPage.Are_you_sure_you_want_to_delete_fixed_from_enumeration).toBeVisible();
    await correspondentPortalPage.Yes_Proceed_Button.click();
    await page.waitForLoadState('networkidle');
    await correspondentPortalPage.Upload_File.setInputFiles(path.resolve(__dirname, 'test-data', "Bid Maps File XLS.xls"));
    await expect(deepikaaugbidqa1csvButtonDivPage.Delete_Button_in_Bid_Maps).toBeVisible();
    await deepikaaugbidqa1csvButtonDivPage.Delete_Button_in_Bid_Maps.click();
    await expect(correspondentPortalPage.Are_you_sure_you_want_to_delete_fixed_from_enumeration).toBeVisible();
    await correspondentPortalPage.Yes_Proceed_Button.click();
    await page.waitForLoadState('networkidle');
    await correspondentPortalPage.Upload_File.setInputFiles(path.resolve(__dirname, 'test-data', "Bid Maps File Txt.txt"));
    await expect(deepikaaugbidqa1csvButtonDivPage.Delete_Button_in_Bid_Maps).toBeVisible();
    await deepikaaugbidqa1csvButtonDivPage.Delete_Button_in_Bid_Maps.click();
    await expect(correspondentPortalPage.Are_you_sure_you_want_to_delete_fixed_from_enumeration).toBeVisible();
    await correspondentPortalPage.Yes_Proceed_Button.click();
    await page.waitForLoadState('networkidle');
    await correspondentPortalPage.Upload_File.setInputFiles(path.resolve(__dirname, 'test-data', "Bid Maps File Pdf.pdf"));
    await expect(fileFormatNotAllowedDeepikaaugbidqa1pdfPage.Error_Message_in_Creation_Of_Bid_Maps).toBeVisible();
  });
});
