// [POM-APPLIED]
import { test, expect } from '@playwright/test';
import path from 'path';
import * as stepGroups from '../../../src/helpers/step-groups';
import { ApplyFiltersButtonPage } from '../../../src/pages/correspondant/apply-filters-button';
import { BidRequestPage } from '../../../src/pages/correspondant/bid-request';
import { ChaseFieldNamePage } from '../../../src/pages/correspondant/chase-field-name';
import { CorrespondentPortalPage } from '../../../src/pages/correspondant/correspondent-portal';
import { FreedomA4187A4187CheckboxPage } from '../../../src/pages/correspondant/freedom-a4187-a4187-checkbox';
import { PriceOfferedPage } from '../../../src/pages/correspondant/price-offered';
import { SpinnerPage } from '../../../src/pages/correspondant/spinner';

test.describe('Unassigned', () => {
  let vars: Record<string, string> = {};
  let applyFiltersButtonPage: ApplyFiltersButtonPage;
  let bidRequestPage: BidRequestPage;
  let chaseFieldNamePage: ChaseFieldNamePage;
  let correspondentPortalPage: CorrespondentPortalPage;
  let freedomA4187A4187CheckboxPage: FreedomA4187A4187CheckboxPage;
  let priceOfferedPage: PriceOfferedPage;
  let spinnerPage: SpinnerPage;

  test.beforeEach(async ({ page }) => {
    vars = {};
    applyFiltersButtonPage = new ApplyFiltersButtonPage(page);
    bidRequestPage = new BidRequestPage(page);
    chaseFieldNamePage = new ChaseFieldNamePage(page);
    correspondentPortalPage = new CorrespondentPortalPage(page);
    freedomA4187A4187CheckboxPage = new FreedomA4187A4187CheckboxPage(page);
    priceOfferedPage = new PriceOfferedPage(page);
    spinnerPage = new SpinnerPage(page);
  });

  test('REG_TS02_TC02.5_Verify show all  and show selected features In Search Filter Dropdown', async ({ page }) => {
    await stepGroups.stepGroup_Login_to_CORR_Portal(page, vars);
    await page.waitForLoadState('networkidle');
    await correspondentPortalPage.Bid_Requests.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await priceOfferedPage.Filter_Dropdown1.click();
    await correspondentPortalPage.Select_CompanyCCode_Dropdown1.click();
    await freedomA4187A4187CheckboxPage.First_Company_Checkbox.check();
    await chaseFieldNamePage.Second_Company_Checkbox.check();
    vars["FirstCompanyName"] = await bidRequestPage.First_Company_Name_Text.textContent() || '';
    vars["SecondCompanyName"] = await correspondentPortalPage.Second_Company_Text.textContent() || '';
    await correspondentPortalPage.Show_Selected_Button.click();
    await expect(bidRequestPage.First_Company_Name_Text).toContainText(vars["FirstCompanyName"]);
    await expect(correspondentPortalPage.Second_Company_Text).toContainText(vars["SecondCompanyName"]);
    await expect(freedomA4187A4187CheckboxPage.First_Company_Checkbox).toBeVisible();
    await expect(chaseFieldNamePage.Second_Company_Checkbox).toBeVisible();
    vars["ExpectedSelectedCompaniesCount"] = String(await correspondentPortalPage.Selected_CompaniesBid_Req_Filters.count());
    // [DISABLED] Store the count of elements identified by locator Total Companies(Bid Request Filters) into a variable TotalShowedSelectedCompiniesCount
    // vars["TotalShowedSelectedCompiniesCount"] = String(await correspondentPortalPage.Total_CompaniesBid_Request_Filters.count());
    vars["ActualSelectedCompaniesCount"] = await correspondentPortalPage.Selected_Items_CountBeside_Apply_Selected.textContent() || '';
    expect(String(vars["ExpectedSelectedCompaniesCount"])).toBe(vars["ActualSelectedCompaniesCount"]);
    await correspondentPortalPage.Show_All_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    vars["TotalCompiniesCount"] = String(await correspondentPortalPage.Total_CompaniesBid_Request_Filters.count());
    expect(String(vars["TotalCompiniesCount"])).toBe(vars["ExpectedSelectedCompaniesCount"]);
    await correspondentPortalPage.Apply_Selected.click();
    await bidRequestPage.Select_Bid_Request_Status_Dropdown.click();
    await correspondentPortalPage.First_Bid_Request_Checkbox.check();
    await bidRequestPage.Second_Bid_Request_Checkbox.check();
    vars["FirstBidRequestText"] = await correspondentPortalPage.First_Bid_Request_Text.textContent() || '';
    vars["SecondBidRequestText"] = await correspondentPortalPage.Second_Bid_Request_Text.textContent() || '';
    await bidRequestPage.Show_Selected.click();
    await expect(correspondentPortalPage.First_Bid_Request_Text).toContainText(vars["FirstBidRequestText"]);
    await expect(correspondentPortalPage.Second_Bid_Request_Text).toContainText(vars["SecondBidRequestText"]);
    await expect(correspondentPortalPage.First_Bid_Request_Checkbox).toBeVisible();
    await expect(bidRequestPage.Second_Bid_Request_Checkbox).toBeVisible();
    vars["ExpectedSelectedBidReqStatusesCount"] = String(await correspondentPortalPage.Selected_Bid_Request_Status.count());
    vars["ActualSelectedBidReqStatusesCount"] = await correspondentPortalPage.Selected_Status_CountBeside_Apply_Selected.textContent() || '';
    expect(String(vars["ExpectedSelectedBidReqStatusesCount"])).toBe(vars["ActualSelectedBidReqStatusesCount"]);
    await correspondentPortalPage.Show_All_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    vars["TotalBidReqStatusesCount"] = String(await correspondentPortalPage.Total_Bid_Req_Statuses_Count.count());
    expect(String(vars["TotalBidReqStatusesCount"])).toBe(vars["ExpectedSelectedBidReqStatusesCount"]);
    await correspondentPortalPage.Apply_Selected2.waitFor({ state: 'visible' });
    await correspondentPortalPage.Apply_Selected2.click();
    await applyFiltersButtonPage.Apply_Filters_Button.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await priceOfferedPage.Filter_Dropdown1.click();
    await bidRequestPage.Clear_All.waitFor({ state: 'visible' });
    await bidRequestPage.Clear_All.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await priceOfferedPage.Filter_Dropdown1.click();
    await correspondentPortalPage.Select_CompanyCCode_Dropdown1.click();
    await expect(freedomA4187A4187CheckboxPage.First_Company_Checkbox).toBeVisible();
    await expect(chaseFieldNamePage.Second_Company_Checkbox).toBeVisible();
    await bidRequestPage.Select_Bid_Request_Status_Dropdown.click();
    await expect(correspondentPortalPage.First_Bid_Request_Checkbox).toBeVisible();
    await expect(bidRequestPage.Second_Bid_Request_Checkbox).toBeVisible();
  });
});
