// [PREREQ-APPLIED]
// [POM-APPLIED]
import { test, expect } from '@playwright/test';
import path from 'path';
import * as stepGroups from '../../../src/helpers/step-groups';
import { CorrespondentPortalPage } from '../../../src/pages/correspondant/correspondent-portal';
import { PriceOfferedPage } from '../../../src/pages/correspondant/price-offered';
import { SpinnerPage } from '../../../src/pages/correspondant/spinner';
import { runPrereq_1389 } from '../../../src/helpers/prereqs/prereq-1389';

test.describe('REG_PriceOffered', () => {
  let vars: Record<string, string> = {};
  let correspondentPortalPage: CorrespondentPortalPage;
  let priceOfferedPage: PriceOfferedPage;
  let spinnerPage: SpinnerPage;

  test.beforeEach(async ({ page }) => {
    vars = {};
    await runPrereq_1389(page, vars);
    correspondentPortalPage = new CorrespondentPortalPage(page);
    priceOfferedPage = new PriceOfferedPage(page);
    spinnerPage = new SpinnerPage(page);
  });

  test('REG_TS10_TC03_Try to perform commit action by selecting a duplicate + valid loan and Verify the bid, loan value, and selected loan count displayed in the Commit Selected Loans popup', async ({ page }) => {

    await correspondentPortalPage.Commitments_Side_Menu.click();
    await correspondentPortalPage.Price_Offered_List_Dropdown.click();
    vars["BidReqIdPriceOffered"] = vars["RequestIDDetails"];
    await correspondentPortalPage.Search_By_Bid_Request_ID_Input.fill(vars["BidReqIdPriceOffered"]);
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await priceOfferedPage.BidReqId_Standard.click();
    await priceOfferedPage.Required_Loan_Num.waitFor({ state: 'visible' });
    await priceOfferedPage.Required_Loan_Num.check();
    await priceOfferedPage.Get_Price_Button.click();
    await priceOfferedPage.Commit_Selected_1_Dropdown.waitFor({ state: 'visible' });
    await priceOfferedPage.Commit_Selected_1_Dropdown.click();
    await priceOfferedPage.Yes_Commit_ButtonPopup.click();
    await priceOfferedPage.Okay_ButtonPopup.waitFor({ state: 'visible' });
    await priceOfferedPage.Okay_ButtonPopup.click();
    await priceOfferedPage.All_Loans_Tabprice_offered_screen.click();
    await priceOfferedPage.Committed_Loan_NumStandard.waitFor({ state: 'visible' });
    vars["CommittedLoanNumStandard"] = await priceOfferedPage.Committed_Loan_NumStandard.textContent() || '';
    vars["UncommittedLoanNumStandard"] = await priceOfferedPage.Uncommitted_Loan_NumStandard.textContent() || '';
    vars["OpenAuthLimitStandard"] = await priceOfferedPage.Open_Auth_Limit.textContent() || '';
    vars["OpenAuthLimitStandard"] = String('').split("(")["0"] || '';
    vars["AuthLimitStandard"] = await priceOfferedPage.Auth_Limit.textContent() || '';
    await priceOfferedPage.BackTo_PriceofferedPage.click();
    await spinnerPage.Spinner.waitFor({ state: 'hidden' });
    await priceOfferedPage.BidReqId_Chase_Direct.click();
    await priceOfferedPage.Check_Fresh_Loan_NumChase_Direct.check();
    await priceOfferedPage.Check_Duplicate_Loan_NumChase_Direct.check();
    vars["SelectedLoansCount"] = String(await priceOfferedPage.Checked_Row.count());
    vars["LoanAmountDuplicateLoan"] = await priceOfferedPage.Loan_AmountDuplicate_Loan_Num.textContent() || '';
    vars["LoanAmountFreshLoan"] = await priceOfferedPage.Loan_AmountFresh_Loan_Num.textContent() || '';
    vars["ExpectedCommittedLoanAmount"] = String(vars["LoanAmountFreshLoan"]).trim();
    vars["TotalSelectedLoanAmount"] = (parseFloat(String(vars["LoanAmountDuplicateLoan"])) + parseFloat(String(vars["LoanAmountFreshLoan"]))).toFixed(0);
    vars["TotalSelectedLoanAmount"] = String(vars["TotalSelectedLoanAmount"]).trim();
    await priceOfferedPage.Get_Price_Button.click();
    await priceOfferedPage.Commit_Selected_1_Dropdown.waitFor({ state: 'visible' });
    await expect(priceOfferedPage.Commit_Selected_1_Dropdown).toBeEnabled();
    await priceOfferedPage.Commit_Selected_1_Dropdown.click();
    vars["BidreqIDPopup"] = await priceOfferedPage.BidRequestIdPopup.textContent() || '';
    vars["LoanValuePopup"] = await priceOfferedPage.Loan_ValuePopup.textContent() || '';
    vars["LoanValuePopup"] = String(vars["LoanValuePopup"]).replace(/\$\,/g, '');
    vars["SelectedLoansCountPopup"] = await priceOfferedPage.Selected_LoansPopup.textContent() || '';
    vars["SelectedLoansCountPopup"] = String(vars["SelectedLoansCountPopup"]).trim();
    expect(String(vars["BidReqIdPriceOffered"])).toBe(vars["BidreqIDPopup"]);
    expect(String(vars["TotalSelectedLoanAmount"])).toBe(vars["LoanValuePopup"]);
    expect(String(vars["SelectedLoansCount"])).toBe(vars["SelectedLoansCountPopup"]);
    await priceOfferedPage.Yes_Commit_ButtonPopup.click();
    vars["space"] = "key_blank";
    vars["DateAndTimeFormat"] = "M/d/yy" + vars["space"] + "h:mm a";
    vars["ExpectedBidCommittedDateAndTime"] = (() => {
      const d = new Date();
      const opts: Intl.DateTimeFormatOptions = { timeZone: "UTC" };
      const fmt = "DateAndTimeFormat";
      // Map Java date format to Intl parts
      const parts = new Intl.DateTimeFormat('en-US', { ...opts, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true }).formatToParts(d);
      const p = Object.fromEntries(parts.map(({type, value}) => [type, value]));
      return fmt.replace('yyyy', p.year || '').replace('yy', (p.year||'').slice(-2)).replace('MM', p.month || '').replace('dd', p.day || '').replace('HH', String(d.getHours()).padStart(2,'0')).replace('hh', p.hour || '').replace('mm', p.minute || '').replace('ss', p.second || '').replace('a', p.dayPeriod || '').replace(/M(?!M)/g, String(parseInt(p.month||'0'))).replace(/d(?!d)/g, String(parseInt(p.day||'0'))).replace(/h(?!h)/g, String(parseInt(p.hour||'0')));
    })();
    await priceOfferedPage.Okay_ButtonPopup.waitFor({ state: 'visible' });
    vars["CommitmentUniqueNumberPopup"] = await priceOfferedPage.Commitment_ID.textContent() || '';
    vars["CommitmentUniqueNumberPopup"] = String(vars["CommitmentUniqueNumberPopup"]).length.toString();
    expect(String(vars["CommitmentUniqueNumberPopup"])).toBe("8");
    await expect(priceOfferedPage.Loans_added_successfullyPopup).toContainText("Loans added successfully -");
    await expect(priceOfferedPage.Commit_Loan_TextPopup).toContainText(vars["UncommittedLoanNumStandard"]);
    await expect(priceOfferedPage.Loans_failedPopup).toContainText("Loans failed to be added to commitment");
    vars["LoanDuplicateMessage"] = "Loan" + vars["space"] + vars["CommittedLoanNumStandard"] + vars["space"] + "is a Duplicate loan. It is already committed";
    await expect(priceOfferedPage.Loans_Failed_TextPopup).toContainText(vars["LoanDuplicateMessage"]);
    await priceOfferedPage.Okay_ButtonPopup.click();
    await page.waitForLoadState('networkidle');
    await priceOfferedPage.All_Loans_PriceofferedPage.click();
    vars["ExpectedCommittedLoans"] = String(await priceOfferedPage.Committed_Loans.count());
    await expect(priceOfferedPage.Committed_Loan_Locked_Icon).toBeVisible();
    vars["CommitmentOrderAllLoans"] = await priceOfferedPage.Commitment_OrderChase_Direct.textContent() || '';
    vars["LastNameAllLoans"] = await priceOfferedPage.Last_Name_Committed_Loan.textContent() || '';
    vars["LoanAmountAllLoans"] = await priceOfferedPage.Loan_Amount_Committed_Loan.textContent() || '';
    vars["InterestRateAllLoans"] = await priceOfferedPage.Interest_Rate_Committed_Loan.textContent() || '';
    vars["ReferenceSecurityAllLoans"] = await priceOfferedPage.Reference_Security_Committed_Loan.textContent() || '';
    vars["ReferenceSecurityPriceAllLoans"] = await priceOfferedPage.Reference_Security_Price_Committed_Loan.textContent() || '';
    vars["GrossPriceAllLoans"] = await priceOfferedPage.Gross_Price_Committed_Loan.textContent() || '';
    vars["HedgeRatioAllLoans"] = await priceOfferedPage.Hedge_Ratio_Committed_Loan.textContent() || '';
    vars["MarketAdjustmentAllLoans"] = await priceOfferedPage.Market_Adjustment_Committed_Loan.textContent() || '';
    vars["CurrentGrossPriceAllLoans"] = await priceOfferedPage.Current_Gross_Price_Committed_Laon.textContent() || '';
    vars["OpenAuthLimit"] = await priceOfferedPage.Open_Auth_Limit.textContent() || '';
    vars["OpenAuthLimitChaseDirect"] = String('').split("(")["0"] || '';
    vars["OpenAuthLimitChaseDirect"] = String(vars["OpenAuthLimitChaseDirect"]).replace(/\$\,/g, '');
    vars["OpenAuthLimitChaseDirect"] = String(vars["OpenAuthLimitChaseDirect"]).trim();
    vars["OpenAuthLimitPercentageChaseDirect"] = String('').split("(")["1"] || '';
    vars["OpenAuthLimitPercentageChaseDirect"] = String(vars["OpenAuthLimitPercentageChaseDirect"]).replace(/\)%/g, '');
    vars["AuthLimitChaseDirect"] = await priceOfferedPage.Auth_Limit.textContent() || '';
    vars["LastCommittedBid"] = await priceOfferedPage.Last_Committed_Bid.textContent() || '';
    vars["ActualCommittedBidDateAndTime"] = String('').split("|")["0"] || '';
    vars["ActualCommittedBidDateAndTime"] = String(vars["ActualCommittedBidDateAndTime"]).trim();
    vars["LatestCommittedBidLoanAmount"] = await priceOfferedPage.Last_Committed_Bid_LoanAmount.textContent() || '';
    vars["ActualCommittedBidLoanAmount"] = String(vars["LatestCommittedBidLoanAmount"]).substring(3);
    await priceOfferedPage.LockedCommitted_Loans.click();
    await priceOfferedPage.Commit_Selected_1_Dropdown.waitFor({ state: 'hidden' });
    await expect(priceOfferedPage.Paste_Loans_ButtonPrice_Offered_Page).toBeVisible();
    vars["ActualCommittedLoans"] = await priceOfferedPage.LockedCommitted_Loans_Count.textContent() || '';
    expect(String(vars["ActualCommittedLoans"])).toBe(vars["ExpectedCommittedLoans"]);
    await expect(priceOfferedPage.Commitment_OrderChase_Direct).toContainText(vars["CommitmentOrderAllLoans"]);
    await expect(priceOfferedPage.Committed_Loan_NumChase).toBeVisible();
    await expect(priceOfferedPage.Duplicate_Loan_NumStandard).toBeVisible();
    await expect(priceOfferedPage.Last_Name_Committed_Loan).toContainText(vars["LastNameAllLoans"]);
    await expect(priceOfferedPage.Loan_Amount_Committed_Loan).toContainText(vars["LoanAmountAllLoans"]);
    await expect(priceOfferedPage.Interest_Rate_Committed_Loan).toContainText(vars["InterestRateAllLoans"]);
    await expect(priceOfferedPage.Reference_Security_Committed_Loan).toContainText(vars["ReferenceSecurityAllLoans"]);
    await expect(priceOfferedPage.Reference_Security_Price_Committed_Loan).toContainText(vars["ReferenceSecurityPriceAllLoans"]);
    await expect(priceOfferedPage.Gross_Price_Committed_Loan).toContainText(vars["GrossPriceAllLoans"]);
    await expect(priceOfferedPage.Hedge_Ratio_Committed_Loan).toContainText(vars["HedgeRatioAllLoans"]);
    await expect(priceOfferedPage.Market_Adjustment_Committed_Loan).toContainText(vars["MarketAdjustmentAllLoans"]);
    await expect(priceOfferedPage.Current_Gross_Price_Committed_Laon).toContainText(vars["CurrentGrossPriceAllLoans"]);
    vars["ExpectedOpenAuthLimit"] = (parseFloat(String(vars["OpenAuthLimitStandard"])) - parseFloat(String(vars["ExpectedCommittedLoanAmount"]))).toFixed(0);
    vars["ExpectedOpenAuthLimitPercentage"] = (parseFloat(String(vars["ExpectedOpenAuthLimit"])) / parseFloat(String(vars["AuthLimitChaseDirect"]))).toFixed(4);
    vars["ExpectedOpenAuthLimitPercentage"] = (parseFloat(String(vars["ExpectedOpenAuthLimitPercentage"])) * parseFloat(String("100"))).toFixed(2);
    expect(String(vars["ExpectedOpenAuthLimit"])).toBe(vars["OpenAuthLimitChaseDirect"]);
    expect(String(vars["ExpectedOpenAuthLimitPercentage"])).toBe(vars["OpenAuthLimitPercentageChaseDirect"]);
    expect(String(vars["AuthLimitStandard"])).toBe(vars["AuthLimitChaseDirect"]);
    expect(String(vars["ExpectedBidCommittedDateAndTime"])).toBe(vars["ActualCommittedBidDateAndTime"]);
    expect(String(vars["ExpectedCommittedLoanAmount"])).toBe(vars["ActualCommittedBidLoanAmount"]);
    // Write to test data profile: "RequestIDfrom10-3" = vars["BidReqIdPriceOffered"]
  });
});
